using UnityEngine;

namespace Underground.World
{
    public class RoadPostProcessor : MonoBehaviour
    {
        public void ProcessAll()
        {
            Debug.Log("RoadPostProcessor: Running racing optimizations globally across all archipelago islands...");

            GameObject mapRoot = GameObject.Find("Epic_Archipelago_Map");
            if (mapRoot == null) return;

            int culledBlocks = 0;

            // Iterate through every FCG Island generated by the Bootstrap
            foreach (Transform island in mapRoot.transform)
            {
                if (island.name.StartsWith("Island_"))
                {
                    foreach (Transform block in island)
                    {
                        // Prune standard dense residential blocks to create large open speed zones
                        // This naturally breaks the repetitive grid layout and creates race tracks
                        if (block.name.Contains("BB") || block.name.Contains("BR"))
                        {
                            // Cul 20% of dense blocks for speed flow
                            if (Random.Range(0, 100) < 20) 
                            {
                                DestroyImmediate(block.gameObject);
                                culledBlocks++;
                            }
                        }
                    }
                }
            }

            Debug.Log($"RoadPostProcessor: Culled {culledBlocks} dense city blocks across all islands to force open areas and fewer 90-degree stops.");
            Debug.Log("RoadPostProcessor: Architecture optimized for high-speed driving.");
        }
    }
}
